### ISSUE TITLE
mutichannel (routing)?

### ISSUE THREAD

**Issue by capoei** [wwmm/easyeffects#1126]
Is there any way to add multi-channel mangement/routing?
just as an example my use case (which would also require the adition of the possibility of a other instance of the convolver):
stereo signal > room correction convolution > crossovers via convolution resulting in 4 channels > routing of channels to my audio interface outputs

**Comment by wwmm** [comment]
>Is there any way to add multi-channel mangement/routing?

Unfortunately not. There are other open issues asking for similar multichannel features too. But integrating them in an application that evolved around stereo audio processing is really hard. From the user interface to our presets system and effects pipeline the amount of changes required to handle multichannel features properly is huge. And to make things harder I do not have a surround system. My speakers are a stereo 2.0 from Edifier. They are good but not suitable to actually develop multichannel features.

As what you ask seems to require that only the output node actually need to have more than 2 outputs it may be a little more doable than what other people are asking. Let's keep this issue open for now.

>which would also require the adition of the possibility of a other instance of the convolver

Like most of the plugins we use our convolver only has 2 input/output ports. A new plugin with capable of output more than 2 channels while having 2 input channels would be required. And it would probably have to be the last plugin in the pipeline.

**Comment by capoei** [comment]
so there is no wa to include a "split" plugin that splits the plugin chain into 2 or more (stereo ones)?
also when I talked about another instance, it is atm not possible even in the stereo chain. I can't put one convolver after another.
and yes, the crossover would be the last in the chain anyways. so mayby it is posssible to make a "output plugin" where you could put other plugins in paralel?

**Comment by capoei** [comment]
the "output plugin" could have a split feature, where on every split you get 2 new outputs with the stereo inputs. that way the 5.1 guys could make 4 chains and control front/back/center/LFE independently on the output

**Comment by wwmm** [comment]
>so there is no wa to include a "split" plugin that splits the plugin chain into 2 or more (stereo ones)?

Not inside EasyEffects. But I think it can be done if you create a PipeWire loopback device and set it as your default output. OR if you select it as EasyEffects output in our device selection menu. Loopback devices should be able to do something close to what you want. Take a look at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1447#note_1006488

**Comment by capoei** [comment]
is it maybe possible to extend the output section in the pipewire tab so that we can select a running aplication as output device?

**Comment by wwmm** [comment]
>is it maybe possible to extend the output section in the pipewire tab so that we can select a running aplication as output device?

It depends on what kind of application you are thinking about. Usually the target application is the one that should be exporting a standard output device that would be naturally visible in our device selection menu.

**Comment by capoei** [comment]
jack standalone apps like the LSP ones.
they wont show up.
but I guess I have to create a sink for this to work and it will show up in
EE

Em dom., 5 de set. de 2021 às 10:50, Wellington Wallace <
***@***.***> escreveu:

**Comment by capoei** [comment]
ok. pw-link is what I need.
never mind

Em dom., 5 de set. de 2021 às 11:18, Fábio Wolarski ***@***.***>
escreveu:

**Comment by capoei** [comment]
still, using pw-link I probably can't avoid EE to connect to the
fiscal device, too?

Em dom., 5 de set. de 2021 às 11:26, Fábio Wolarski ***@***.***>
escreveu:

**Comment by capoei** [comment]
ok,
I just created a dummy device to select in EE

pactl load-module module-null-sink

Em dom., 5 de set. de 2021 às 11:27, Fábio Wolarski ***@***.***>
escreveu:

**Comment by capoei** [comment]
ok.  I use pactl to create a selectable device in EE and manage the conections with pw-link.

**Comment by wwmm** [comment]
>ok. I use pactl to create a selectable device in EE and manage the conections with pw-link.

In these cases where a very specific solution is needed this is probably the better option. It will give you more flexibility.

**Comment by Digitalone1** [comment]
@capoei which distribution are you using? Could you install easyeffects-git from AUR or compile from source to test the upmixing feature that I'd like to integrate in the application (only for the streaming coming from the output pipeline)?

**Comment by capoei** [comment]
I understand the limitations, but I think it is possible to dream of an
all-in-on DSP solution like equalizer-APO is for Windows.
Now, obviously Pipepire is still in heavy development and I am thankful EE
exists already at this early stage.


Em dom., 5 de set. de 2021 às 12:30, Wellington Wallace <
***@***.***> escreveu:

**Comment by capoei** [comment]
> @capoei which distribution are you using? Could you install easyeffects-git from AUR or compile from source to test the upmixing feature that I'd like to integrate in the application (only for the stream coming from the output pipeline)?

just installed easyeffects-git-6.1.0.r30 from AUR. 
couldn't find said feature. is it suposed to appear in the plugin list?

**Comment by Digitalone1** [comment]
> > @capoei which distribution are you using? Could you install easyeffects-git from AUR or compile from source to test the upmixing feature that I'd like to integrate in the application (only for the stream coming from the output pipeline)?
> 
> just installed easyeffects-git-6.1.0.r30 from AUR.
> couldn't find said feature. is it suposed to appear in the plugin list?

No, I will add it in the next days.

I will notice you when it's ready.

**Comment by capoei** [comment]
ok

**Comment by Digitalone1** [comment]
@capoei unfortunately the solution I implemented a month ago it's not working anymore. 

Until Pipewire does not introduce an easy and transparent way to do channel remapping, or @wwmm to find some better solution, this issue won't be resolved.

 @capoei I recommend you to return to stable easyeffects from Arch upstream repository.

**Comment by capoei** [comment]
gotcha

**Comment by capoei** [comment]
this filter chain stuff is not usefull? https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Filter-Chain#virtual-surround

**Comment by wwmm** [comment]
>this filter chain stuff is not usefull?

The filter chain is designed for people that want to set a few filters  by editing a few configuration files. It is not convenient for use in third party tools. Setting parameters for it on the fly or getting input and output levels will probably be a pain. Assuming it is even possible.

**Comment by Digitalone1** [comment]
Indeed this should be done by Pipewire in a transparent way, as it is done with resampling.

**Comment by Digitalone1** [comment]
@capoei if you can test, make a PKGBUILD text file with the following content: https://pastebin.com/ANi6e62u

And install with 

```
makepkg -sri
``` 

Open dconf, locate

```
/com/github/wwmm/easyeffects/loopback-mode
```

and set it TRUE. Close easyeffects from terminal:

```
easyeffects -q
```

Restart it and play something. Let me know if the channel remapping is working.

**Comment by capoei** [comment]
![Screenshot_20210927_145736](https://user-images.githubusercontent.com/22452408/134960611-fe4b2a5e-2892-472a-82c9-cc3fb1d692ff.png)

**Comment by JohnyPeaN** [comment]
Hi @Digitalone1, could the loopback test fork be brought up to date with master or even merged? I'm using that fork for a while and it is usable. Its at least better solution than no solution.

**Comment by Digitalone1** [comment]
@JohnyPeaN Can you link it here? I made it months ago, don't even remember it.

**Comment by Digitalone1** [comment]
@JohnyPeaN are you using #1171? As far as I remember, it was working to me, but then Pipewire upgraded and I was not able to get it working anymore. Is it working to you?

**Comment by JohnyPeaN** [comment]
This one.
[https://github.com/Digitalone1/easyeffects/tree/loopback](https://github.com/Digitalone1/easyeffects/tree/loopback)
Its version 6.1.2 so those commits are quite off and don't apply.

**Comment by JohnyPeaN** [comment]
> @JohnyPeaN are you using #1171? As far as I remember, it was working to me, but then Pipewire upgraded and I was not able to get it working anymore. Is it working to you?

Yes, seems to be the same. Working here on newest pipewire (0.3.51).

**Comment by Digitalone1** [comment]
Are you sure this is working? I tested the loopback on my stereo stream and I get no output. Which distribution are you using?

**Comment by Digitalone1** [comment]
> > @JohnyPeaN are you using #1171? As far as I remember, it was working to me, but then Pipewire upgraded and I was not able to get it working anymore. Is it working to you?
> 
> Yes, seems to be the same. Working here on newest pipewire (0.3.51).

Which distribution?

Anyway I'd like to try. I don't assure it will be merged, but at least I can try to make it work.

**Comment by JohnyPeaN** [comment]
> > > @JohnyPeaN are you using #1171? As far as I remember, it was working to me, but then Pipewire upgraded and I was not able to get it working anymore. Is it working to you?
> > 
> > 
> > Yes, seems to be the same. Working here on newest pipewire (0.3.51).
> 
> Which distribution?
> 
> Anyway I'd like to try. I don't assure it will be merged, but at least I can try to make it work.

Thanks, that would be great. If it has to be enabled by user, hopefully shouldn't break for others. If you need testing, let me know.

**Comment by Digitalone1** [comment]
So you see an `EasyEffects Channel Remapping Loopback` stream in pavucontrol all the time?

**Comment by JohnyPeaN** [comment]
> So you see an `EasyEffects Channel Remapping Loopback` stream in pavucontrol all the time?

Sorry `EasyEffects Channel Remapping Loopback` is visible in graph, not in pavucontrol. In pavucontrol only `EasyEffects Sink` and `EasyEffects Loopback Sink` are added as outputs:
[https://imgur.com/a/1tdlHtf](https://imgur.com/a/1tdlHtf)

**Comment by Digitalone1** [comment]
Do you see also something by Easyeffects in the first tab (Players) of pavucontrol?

Anyway I could try it out in the next week.

**Comment by JohnyPeaN** [comment]
Yes, output from media application goes to `EasyEffects Sink`. The path from `EasyEffects Loopback Sink` to sound card isn't visible on first tab in pavucontrol.

![Screenshot_Volume Control_1](https://user-images.githubusercontent.com/20441146/170963364-5dc9b28e-9db6-4c92-bf0d-40c83781c3eb.png)

**Comment by Digitalone1** [comment]
Please change the combobox in the bottom bar to `All Streams`, you should see also the loopback sink.

You should also be able to switch from `EasyEffects Sink` to the loopback sink in the combobox related to the application (do not do it anyway).

Because of the reasons above, we did not implement a loopback sink because that could lead to confusion in users.

Pipewire should provide an easy way for us to make the upmixing, but for now it seems not possible because we are forced to manually link the last filter to the chosen output device/sink.

A workaround for this issue could be showing the loopback sink into our output device list, so you can choose it and Pipewire will do the upmixing on it's own to the speakers.

Can you generate a lookback sink and check if it is selectable from the output device in the latest EasyEffects version?

Take a look [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#loopback) on how to set a lookback sink. You should manually link it to the speaker in helvum.

**Comment by JohnyPeaN** [comment]
Thanks, you are right. It is in hidden streams:
![Screenshot_Volume Control_2](https://user-images.githubusercontent.com/20441146/171004349-dc61f10b-41a5-4b3b-a4ae-06ceb1a55415.png)


Regarding the loopback in latest easyeffects is this what you meant?:
![Screenshot_EasyEffects_1](https://user-images.githubusercontent.com/20441146/171004294-59c681b9-d354-46c5-a1bc-8e1b4dbeb0ac.png)
I created it with pw-loopback

**Comment by Digitalone1** [comment]
Check if you can select it as output device in `Pipewire` tab.

**Comment by Digitalone1** [comment]
But before exclude it from Applications list in EasyEffects, then link it to your speaker.

**Comment by JohnyPeaN** [comment]
Added loopback to Excluded Apps (disapeared from list), linked it to speakers with pavucontrol and it cannot be selected in easyeffects PipeWire tab as output. Doesn't show up in device list.

**Comment by Digitalone1** [comment]
Okay, but is the lookback sink playing to your speakers?

You should be able to redirect it to your speakers through pavucontrol

The scheme should be like this in `Helvum`:

> app output audio -> EasyEffects Sink -> various effects link compressor/equalizer -> Output_Level filter -> loopback sink

And

> loopback output > multichannel speakers

You could redirect the output from loopback sink to the speakers in pavucontrol. If everything works and Pipewire if configured properly, you should have the upmixing working.   

Anyway, we should do some code refactoring to ignore loopback streams in EE app list and add loopback device in output devices list to be selectable.

**Comment by JohnyPeaN** [comment]
It works as you described with new easyeffects:
![Screenshot_20220414](https://user-images.githubusercontent.com/20441146/171026038-44ea4462-4d44-4dbe-937c-ca413b954289.png)
Is this actually what loopback branch did?

All channels playing with effect applied. If I bypass the effect, the difference can be heard. If I disable and enable the stream (in EE) it breaks the graph and playback.

Disable:
![Screenshot_20220415](https://user-images.githubusercontent.com/20441146/171026059-3a62066d-342b-441f-98c8-0120c6d1a60b.png)

Reenable:
![Screenshot_20220416](https://user-images.githubusercontent.com/20441146/171026093-663c5a6e-9885-448e-a5f9-d0e79ca05637.png)

I suppose this does make sense, since EE doesn't manage the loopback as output. Some times enable action cause the stream to get "suspended" and enable check imeediatelly dissapears. Connection graph is the same as in third picture but playback stops.

**Comment by Digitalone1** [comment]
No, the loopback branch was an attempt to test a loopback device loaded by EasyEffects. But it's too hard to manage for us and it's highly error prone (it wasn't even working when I tested it many months ago).

Ideally Pipewire would offer us a way to link the output_level filter to the multichannel output device so that the upmixing is automatically done, but this is not possible. The only way this works is by linking streams to sinks. But it does not work linking filters to sinks: so we have to do it manually and no upmixing can be performed.

When the effects order changes or the enable checkbutton is toggled, EasyEffects remake all the connections, that's why you loose the upmixing and the "graph is broken".  

To solve this issue some tasks have to be done:

- [ ] Hide loopback devices from EE application list and ignore them like we do with monitor streams
- [ ] Show loopback devices in output devices list inside EE Pipewire tab so that the user can select them

The user still have to redirect the output lookback to the multichannel speaker, but at least it will work, even if effects are changed.

@wwmm Any hint on how to detect lookback devices? Have they a specific property? Should we show virtual devices in the output device list to let the user handle these kind of configurations (not the EasyEffects sink obviously)?

**Comment by JohnyPeaN** [comment]
Thanks for the explanation. If I understand correctly, with this solution, user would need to preconfigure loopback and EE would allow them to select it as output device. Then rebuilding connections would work correctly. That would be better than the situation we have.
Before finding your loopback branch a while back I was actually trying the manual loopback way, but couldn't find a way to automatically connect EE output to the loopback and make it stick.
I think user can create loopback device already connected to specific sink. I'm not sure how it goes for source, when nothing is specified it connects to preffered capture device.

**Comment by Digitalone1** [comment]
> Thanks for the explanation. If I understand correctly, with this solution, user would need to preconfigure loopback and EE would allow them to select it as output device. Then rebuilding connections would work correctly. That would be better than the situation we have.

Exactly. Keep using the loopback branch for now. Maybe in the next weeks I should be able to implement the fix mentioned above so you could use the master branch.

> I think user can create loopback device already connected to specific sink. I'm not sure how it goes for source, when nothing is specified it connects to preffered capture device.

Yes, try to experiment with the commands listed here: https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#loopback

**Comment by JohnyPeaN** [comment]
Ok, will do both. Thanks.

**Comment by wwmm** [comment]
>@wwmm Any hint on how to detect lookback devices?

As I do not use loopback devices I am not sure. But if we are lucky there is some tag telling it is a loopback. THe thing is I am not sure it is a good idea to just ignore them. A long time ago in PulseEffects there were people with valid reasons to apply effects to loopback streams. I think these devices are useful when redirecting smartphone audio to the computer through a bluetooth connection. I would have to find the issue where this was discussed.

>Should we show virtual devices in the output device list to let the user handle these kind of configurations (not the EasyEffects sink obviously)?

Virtual sources should already be visible. I am not sure about virtual sinks. But I think it is a good thing to do as long our own virtual sink is not shown in the process.

**Comment by wwmm** [comment]
>I would have to find the issue where this was discussed.

I've found it https://github.com/wwmm/easyeffects/issues/567#issuecomment-529735799. Blocking loopback streams by default is not a good idea.

**Comment by Digitalone1** [comment]
Okay, the user should exclude it on their own.

**Comment by Digitalone1** [comment]
@JohnyPeaN you can already do it with the latest release.

The pipewire loopback in the default configuration loads an input and an output stream. Both do not show in device lists because they are streams.

If you load the pipewire loopback in an alternative way:

```
pw-loopback -m '[FL FR]' --capture-props='media.class=Audio/Sink'
```

A sink and an output stream are spawned, so you can select the sink as the output device in EasyEffects.

Anyway it's still tricky because every time the loopback is created, it changes name. For this reason you have to manually set the output device and exclude the loopback output stream in EasyEffects anytime the loopback configuration is generated. The exclusion is crucial because with Process All Output Stream set, the output loopback will fee our EasyEffects Sink.

Unfortunately I can't see a way to set the name of the nodes (even with the examples shown on the Pipewire Wiki posted above because it only sets the description on the sink). You can open a ticket on Pipewire Issue for this.

Anyway, it should work.

**Comment by wwmm** [comment]
>This sets a decent name in my computer

I meant to say a decent name for the devices. The stream related to the loopback and shown in our Players/Recorders tab will still be super ugly.

**Comment by Digitalone1** [comment]
Indeed the name is not persistent and the loopback stream cannot be excluded. Unless there's a way to set the app id string on it. I don't know if it's possible.

**Comment by wwmm** [comment]
Maybe to change the playback stream tags we also have to pass `--playbacke-props` and set something there

**Comment by wwmm** [comment]
This changes the stream name
```
pw-loopback -m '[ FL FR]' --capture-props='media.class=Audio/Sink node.name=myloop node.description=MyLoop' --playback-props='node.name=myloop_playback node.description=MyLoop_Playback'
```

**Comment by JohnyPeaN** [comment]
Can confirm. This loopback can be excluded and persistently selected in output devices. Works on 2ch output. Will test later on 5.1.

**Comment by JohnyPeaN** [comment]
Managed to achieve quite working scenario:

EE:
autorun = on
manage all outputs = off
profile autoload

`~/.config/pipewire/pipewire.conf.d/10-my-loop.conf`
```
context.modules = [
	{   name = libpipewire-module-loopback
		args = {
			audio.position = [ FL FR ]
			capture.props = {
				media.class = Audio/Sink
				node.name = myloop
				node.description = "MyLoop"
			}
			playback.props = {
				node.name = myloop_playback
				node.description = "MyLoop_Playback"
		       }
		}
	}
]
```
I added `myloop_playback` to excluded list.
![Screenshot_EasyEffects_4](https://user-images.githubusercontent.com/20441146/172222303-97578a56-a6e3-4520-a4a7-228c27b469e6.png)

Manually configured `MyLoop` in pipewire tab > Output Device
![Screenshot_EasyEffects_2](https://user-images.githubusercontent.com/20441146/172218567-bf6a4a5e-5f2c-4110-94ed-061903101c4e.png)
![Screenshot_20220417](https://user-images.githubusercontent.com/20441146/172218581-40bf9c80-f888-401a-b241-4f66561c4e60.png)
Loopback device is automatically created with fixed name, EE starts and correctly uses it. Enabled application then get connected through EE, and loopback ( providing upmix ) to default sink. Other applications connect dirrectly to default sink.

Even switching output devices  2ch <> 5.1ch back and forth works on the fly and loopback enables/disables upmix.

This is persistent, no need to create and connect loopback by hand everytime and seems to be working great. Will use it this way to see if it has some caveats.

**Comment by Winnus** [comment]
Thank you !
The solution above worked out of the box for me.

**Comment by Digitalone1** [comment]
@wwmm I think this issue should be stuck in place of #1216 and the title modified in `Multichannel routing on EasyEffects`.

**Comment by ClumsyDerp** [comment]
> ![Screenshot_20220417](https://user-images.githubusercontent.com/20441146/172218581-40bf9c80-f888-401a-b241-4f66561c4e60.png) Loopback device is automatically created with fixed name, EE starts and correctly uses it. Enabled application then get connected through EE, and loopback ( providing upmix ) to default sink. Other applications connect dirrectly to default sink.

Stumbled across the same problem and wound up here eventually.

I've read through most of this issue and tried to understand what I could.

In my particular case I couldn't get it to work just yet, as using either EE or JamesDPS on my virtual surround sink causes all sound to just disappear all while only being stereo on top of it. That said, I've been wondering what tool/command is being used in the provided screenshot. It appears to be a part of common knowledge I seem to be missing or couldn't pick up on reading through this thread. Futher it could help me resolve my particular issue(s).

If anyone could point me towards the correct direction it'd be much appreciated.

**Comment by Digitalone1** [comment]
@ClumsyDerp the tool is helvum. But you don't really need it. Just install pavucontrol and redirect the loopback output to the multichannel device.

**Comment by ClumsyDerp** [comment]
Tinkered around with the tools but it appears I got a different setup from JohnyPean.

[Helvum Screenshot](https://i.imgur.com/ObVFpOR.png) (attempted to recreate JohnyPean's setup)

Bottom line: The ADI 2 DAC is my actual physical device and only has two channels as shown by helvum and is entirely bypassed in my example, which strikes me as wrong - or rather, I'd have to somehow throw eight channels into two. From my limited understanding I may just be sending my sound in circles right now, if even that 🤡

The "Virtual Surround Sink" is a "fake" Pipewire 7.1 sink, as per their [example](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/daemon/filter-chain/sink-virtual-surround-7.1-hesuvi.conf).

Desired outcome: Apply EE equalizer features but retain 7.1 virtual surround.

**Comment by Digitalone1** [comment]
You should enable Firefox in EasyEffects. EasyEffects should be set to output to `myloop` (as it seems to already be configured).

Then you go in Pavucontrol and redirect `myloop_playback` to the DAC.

**Comment by Digitalone1** [comment]
For what I said, which is the usual configuration, you won't get the up/downmix because the DAC is only 2 channels.

For what you want, it seems the virtual surround you got is not enough because the 7.1 virtual surround sink is not an output stream. So you can't redirect it in pavucontrol.

You could try to send EasyEffects to 2.0 Virtual Surround Sink and to to redirect the 7.1 Virtual Surround Sink to the DAC. But I'm afraid you can't do it from pavucontrol and the only option is doing it manually, which is not a true downmix like you you wanted.

**Comment by Digitalone1** [comment]
Oh, now I see from the `sink-virtual-surround-7.1-hesuvi.conf` that the capture is the 7.1 and the playback is the 2.0, so I think want you want can't be done because we don't have a way to upmix from 2 to 8 channels.

The upmix we suggested here is happening because fortunately we can link 2 channel filters to 2 channel virtual sinks. Then Pipewire does the upmix on its own. 

For what you want, you need first an upmix and then a downmix. That configuration is not good and EasyEffects can't do both.

**Comment by wwmm** [comment]
>The ADI 2 DAC is my actual physical device and only has two channels as shown by helvum
>Desired outcome: Apply EE equalizer features but retain 7.1 virtual surround.

Even without EasyEffects in the way it does not make much sense to me to create this kind of virtual surround if your sound card has only 2 channels. If I am not mistaken the virtual surround created by PipeWire and Pulseaudio is intended for hardware that actually have all these channels. So even without EasyEffects you won't be retaining the 7.1 surround. It will be downmixed to stereo. Am I missing something here?

**Comment by ClumsyDerp** [comment]
> > The ADI 2 DAC is my actual physical device and only has two channels as shown by helvum
> > Desired outcome: Apply EE equalizer features but retain 7.1 virtual surround.
> 
> Even without EasyEffects in the way it does not make much sense to me to create this kind of virtual surround if your sound card has only 2 channels. If I am not mistaken the virtual surround created by PipeWire and Pulseaudio is intended for hardware that actually have all these channels. So even without EasyEffects you won't be retaining the 7.1 surround. It will be downmixed to stereo. Am I missing something here?

I can't argue for pipewire's way of handling things, as well as potential magic that is going on under the surface but I can vouch for a spacial upgrade compared to stereo and all directions seem to be fully in tact. It's comparable, if not exceeding Window's spacial sound API - in this instance compared to DTS:X, which I also use/own.

If you happen to own a pair of headphones feel free to try it out for yourself, it only takes a few minutes.

Simply copy the file content from `{ name = libpipewire-module-filter-chain [...] }` into your pipewire.cfg's `context.modules = [...]` section and replace the `hrir.wav`'s references to an actual reference file on your system.

**Comment by wwmm** [comment]
>It's comparable, if not exceeding Window's spacial sound API - in this instance compared to DTS:X, which I also use/own.

Interesting. I had the impression that the downmixing to stereo would kill spatial feeling that had been added by the virtual surround.

But in this case I do not see why a custom loopback device between your virtual surround sink and EasyEFfects virtual sink should not work. I admit I did not read all the conversation in detail because I am at my work now. But if downmixing is not a a problem a loopback from 7.1 to stereo should work.

**Comment by Digitalone1** [comment]
- Firefox 2.0 -> EasyEffetcts Sink 2.0 -> MyLoop 2.0 (in EasyEffects enable `Firefox`, add `MyLoop` in excluded apps and set `MyLoop` as EasyEffects output)
- MyLoop_Playback 7.1 -> Virtual Surround Sink 7.1 (redirect in pavucontrol, add `Virtual Surround Sink` in EasyEffects excluded apps list)
- Virtual Surround Sink 2.0 -> ADI-2 DAC 2.0 (redirect in pavucontrol)

Try it. Maybe you're lucky.

**Comment by ClumsyDerp** [comment]
Unfortunately did not work, but I might as well been doing something wrong.

[Picture](https://i.imgur.com/rGEZ5Sz.png).

I pretty much build what you've suggested, haven't done anything with pavucontrol yet, though.

Additional info:
* Firefox was playing back a video, so there was audio playing
* I've cycled all playback devices with both 7.1 sink in EE enabled and disabled an no constellation caused EE to pick up on any "output"
* `MyLoop` is set as output

I'll dig a bit into pavucontrol.

Cheers.

**Comment by Digitalone1** [comment]
Close Plasma System Settings, it won't help you.

You have to redirect the streams with pavucontrol (install it if you does not have it).

Uncheck the enable checkbutton for virtual surround in EasyEffects (leave it excluded).

In Pavucontrol, first tab (Players), MyLoop_Playback to Virtual Surround and Virtual Surround Sink to ADI DAC.

**Comment by ClumsyDerp** [comment]
Hope this is what it's supposed to be; opening Pavucontrol makes a mess of helvum 🤡

No idea why MyLoop_Playback receives two PulseAudio Volume Controls.

Beyond that the only way to get sound of FF is to route it against the ADI DAC directly and then neither EE works, nor the surround sound.

**Comment by Digitalone1** [comment]
In pavucontrol is everything good. The issues are firefox going into dac and virtual surround going to dac. Remove those links from helvum.

**Comment by ClumsyDerp** [comment]
Hey, sorry for the late response. Sleep, work, you know the drill.

That said, I got good news. Some of the mess cleaned itself up (MyLoop_Playback no longer has two PulseAudio Volume Controls) upon boot and it now works as expected and further the way you laid out above.

[Link](https://i.imgur.com/4HX5WPR.png)

Sorry for hijacking this particular issue, should it have been misplaced.

Thanks for the support, much appreciated and if nothing else I hope it'll serve others down the line.

Cheers!

**Comment by rijnhard** [comment]
this is probably a naive comment, but if I have to think about my dream scenario for multi-channel audio handling, 

```
multi channel source
          --> (filter all channels) e.g. some funny bunch of filters I slap together for my own Dynamic Range Compression
          --> (start individual channel filters) 
                   | -> FR/FL  --> (2 chan filter) 
                   | -> Centre --> (1 chan filter)
                   | -> RL/RR  --> (2 chan filter)
          --> (end individual channel filters) 
          --> (filter all channels)
          --> FFmpeg encoding for output format
```

I remember back when I used windows, with K-Lite I used to construct filter & processing graphs in all sorts of weird and wonderful ways. and then re-encode the output so that I could feed it into a sound card or a receiver over HDMI.

**Comment by rijnhard** [comment]
(barring the FFmpeg part which I think is really out of scope unless somehow the output can marked as passthrough for pipewire) 

a structure like that could be really flexible for anyone wants to handle any kind of processing,
the choice to combine 2 channels together for a 2channel filter for example is also pretty useful.

it doesn't directly solve upmixing or downmixing but can be a good structural building block for how to cater for that later on.

**Comment by wwmm** [comment]
>this is probably a naive comment, but if I have to think about my dream scenario for multi-channel audio handling,

I would not call it naive. In a multichannel setup it is a reasonable expectation to be able to apply different filters for each channels. It just isn't what EasyEffects evolved for. An approach similar the Windows EQualizer APO would make more sense in this case.

>Probably the biggest consequence is that filters need to be aware of how many channels they can accept and how many the pipe is trying to provide it, which it shouldn't allow if there's a mismatch.

There are 2 ways to create filters in PipeWire but if I remember well in both of them you have to hardcode the number of filter channels. So the filter would probably have to be made by default with a large number of channels.

But the worse is dealing with third party filters that are designed for stereo. I think that the Windows Equalizer APO uses its own filters for everything. What makes things a lot easier. But most of the ones used in EasyEffects are LV2 filters designed for stereo.

**Comment by rijnhard** [comment]
> I would not call it naive. In a multichannel setup it is a reasonable expectation to be able to apply different filters for each channel. It just isn't what EasyEffects evolved for. An approach similar the Windows EQualizer APO would make more sense in this case.

So that would mean a rearchitecture, ouch. Painful. If that were to happen then you would want to basically make it a graph engine. 

> There are 2 ways to create filters in PipeWire but if I remember well in both of them you have to hardcode the number of filter channels. So the filter would probably have to be made by default with a large number of channels.

I don't think this is a problem really. I'll elaborate below. 

> But the worse is dealing with third party filters that are designed for stereo. I think that the Windows Equalizer APO uses its own filters for everything. What makes things a lot easier. But most of the ones used in EasyEffects are LV2 filters designed for stereo.

You don't actually need full multi channel support on every filter, most will work fine applied to a single or 2 channels, and with a bit of elbow work and some ui magic (linking a couple instances of the same filter together) you could use 2 channel filters pretty effectively.

With a good foundation you can always work on a specific set of filters being multi channel, or the community can. To be a bit cheeky I don't think that's really the goal here. Of course that's the dream, but not the starting point, but comparison easy effects is still a young project, so I don't think anyone expects it to solve all those rather complex problems in a short timeline.

Of course this is all subject to your vision for it and what you want it to be at the end of the day.

**Comment by wwmm** [comment]
>So that would mean a rearchitecture, ouch. Painful.

Very painful. When I started this project I had things like Viper4Android in mind. And as I have a stereo sound system stereo audio inevitably became a central point in EasyEffects design. 

>You don't actually need full multi channel support on every filter, most will work fine applied to a single or 2 channels, and with a bit of elbow work and some ui magic (linking a couple instances of the same filter together) you could use 2 channel filters pretty effectively.

As multichannel support is never going to happen to third party stereo plugins ignoring one of the 2 channels would be the only option when trying to apply them in a surround setup. Technically it will probably work but there are some annoyances. Our graphical interface will still try to show 2 level meters for example. So besides the special handling to links in the pipeline the plugin window would have to adapt to each scenario and showing only what makes sense. Nothing particularly complicated to ensure. But I would expect other small inconsistencies to show themselves along the way.

There are also plugins that do not make any sense at all outside of a stereo setup and that we would have to make sure are never  added to multichannel processing. The crossfeed and the stereo tools plugins are one example.

But the hard part is that we would be essentially talking about one pipeline for each surround channel. At the end of the day this is what would happen with plugins that have only one or two channels. Handling them and allowing the user to configure them through our window would be quite challenging considering that PipeWire may change the sound card profile at any moment. 

>Of course this is all subject to your vision for it and what you want it to be at the end of the day.

I think it would be super cool to support multichannel. But I have to be realist. With the main developers (me and @Digitalone1) being stereo users and the amount of work necessary for proper multichannel support being really big I do not see this happening even in the far future. Maybe once we finally start to support multiple filter instances a good solution comes to my mind. But at this moment it feels like a distant dream.

**Comment by ilippert** [comment]
with respect to https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1147748628

> This is persistent, no need to create and connect loopback by hand everytime and seems to be working great. Will use it this way to see if it has some caveats.

I agree that it works across boots, great.

However, when I send my computer to sleep/suspension, the loop device stops subsequently working. I reboot, and then it works again.

**Comment by wwmm** [comment]
>However, when I send my computer to sleep/suspension, the loop device stops subsequently working. I reboot, and then it works again.

It may be worth to tell this to PipeWire developers. If only the loopback is not coming back after the PC sleeps it may be a bug on their side.

**Comment by ilippert** [comment]
> It may be worth to tell this to PipeWire developers.
done  – https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2862

**Comment by kode54** [comment]
What about upmixing mono playback sources to stereo? Is there a filter I can add that will only upmix as necessary?

**Comment by wwmm** [comment]
>What about upmixing mono playback sources to stereo? Is there a filter I can add that will only upmix as necessary?

There is the `Stereo Tools` plugin but it is not going to do it ondemand only to what is necessary. It will change the stereo matrix of everything that is passing through the effects pipeline. The reason is that there is only one output/input effects pipeline.

**Comment by b1r63r** [comment]
I think my proposed roadmap would be

1) offer the same number of inputs as the selected output
coding would then be limited to handling the difficulties in switching number of inputs when output switches etc.
run effects only on the front stereo speakers and pass everything else through unchanged.
this would of course lead to some timing issues between channels, but ok for now.

2) add basic timing adjustments for individual channels
these must be tied to the selected output since 5.1 speaker system needs different timings than a 5.1 headphone.

3) add handling of the subwoofer channel.
offer the ability to remove the sub channel from what is presented to the clients so that filtering on the front channels includes low frequency signal. then apply a 2.0 -> 2.1 filter that directs lf output to the sub (of course given that the selected output is one with a subwoofer channel). this way the subwoofer gets integrated into the filter chain without having to deal with true multi channel yet.

4) think hard about how to do proper multi channel filtering.
maybe by implementing a multi-channel equalizer as first step, keep lv2 effects as 2 channel only, and define a way to make new multi channel filters. Maybe there is a standard already for multi channel plugins?

i think this would give the fastest path to enabling a useable multi-channel easyeffects. then let it evolve from there.

**Comment by werickson24** [comment]
Hopefully this could be implemented to a small degree for basic 2.1 audio setups. I just spent easily 6 hours trying to get pipewire to upmix and output to my subwoofer for stereo music (and it still isn't working for a flatpak). It would be beyond amazing if this could've just been an easy effects feature to have some way to clone or mix a stream for the sub channel output, like an option inside the stereo tools.
