### ISSUE TITLE
Sporadic audio crackling

### ISSUE THREAD

**Issue by Exioncore** [wwmm/easyeffects#1567]
### EasyEffects Version

0.3.52 (Built from the repo on 11 June 2022)

### What package are you using?

Other (specify below)

### Distribution

Fedora 36

### Describe the bug

The audio will sporadically crackles. Easiest way to trigger it is just simply listening to Youtube and either clicking on the Fedora Audio device selector from the task bar OR receiving a Discord notification, Either one of the two ALWAYS causes the audio to crackle.

The effects I am running are Autogain, Bass Enhancer, Bass Loudness and Crystalizer.

Things I have tried so far to solve the issue is following these instructions here to no avail:
https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Performance-tuning
I created the file /etc/security/limits.d/95-pipewire.conf with the contents at the link as well as modified the file /usr/lib/systemd/system/rtkit-daemon.service and the file /etc/sysconfig/rtkit again as instructed at the link.

My question is, how can I further tweak either one of those files to solve this crackling issue? I am fairly new to using Linux and so I don't quite know what to touch (does the file /etc/security/limits.d/95-pipewire.conf even matter if I do have rtkit running for instance?)

Looking at htop, pipewire and pipewire-pulse processes jump between PRI of 9 and -89, whilst NI is always -11.

Please let me know if you need any additional information and how to collect it.

Main System Specs:
AMD Ryzen 9 5900x
Focusrite Scarlett Solo
Arctis Pro Wireless

### Expected Behavior

No crackling

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>My question is, how can I further tweak either one of those files or, what else can I do to solve this crackling issue?

The first thing to do in these situations is verifying if the crackling is happening when a specific plugin is used. In this case I am thinking about the crystalizer. It is a very heavy plugin and it has to do some buffering. So there is a chance a crackling happens when PipeWire changes latency on the fly.

Through the command `pw-top` you can try to see if the latency is changing at the same time the crackling happens. The `QUANT` and the `RATE` columns are the ones you want to look at.

**Comment by wwmm** [comment]
>Easiest way to trigger it is just simply listening to Youtube and either clicking on the Fedora Audio device selector from the task bar OR receiving a Discord notification

Discord's app is an endless source of problems. But I am not aware of this `Fedora Audio device selector`.  Changing devices in PAvucontrol causes a crackling?

**Comment by wwmm** [comment]
You can try to temporarily set a fixed latency following the `quantum range` section at https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#quantum-ranges

**Comment by Exioncore** [comment]
> > Easiest way to trigger it is just simply listening to Youtube and either clicking on the Fedora Audio device selector from the task bar OR receiving a Discord notification
> 
> Discord's app is an endless source of problems. But I am not aware of this `Fedora Audio device selector`. Changing devices in PAvucontrol causes a crackling?

I mean this panel here, just simply bringing it up always causes a crackle: 
![image](https://user-images.githubusercontent.com/5459344/173226919-09272e66-c0e7-44c5-9ef3-adae3842fe1f.png)

Steam notifications also will cause a crackle from time to time. In the meantime I will try your suggestion and report back.

**Comment by Digitalone1** [comment]
That's the volume panel from Plasma, right? I suppose the issue comes from them and how they pick all the streams. Do you hear the same crackling also opening pavucontrol?

**Comment by Exioncore** [comment]
After using it for some time, it would seem that indeed setting a fixed quantum rate reduces a lot the number of times I get a crackle. It also crackles every time I do change the quantum rate or that I do see it change just like you suspected. 
The Crystalizer also seems to be the main culprit for it.

For the volume panel that is Plasma indeed. Dunno about pauvcontrol, I don't seem to have that.

**Comment by piorrro33** [comment]
I can confirm the issue and reproduce the "crackling" by switching between `clock.force-quantum = 1024` and `clock.force-quantum = 8192` with just the Convolver.
However, I can not reproduce it after removing all plugins.

**Comment by piorrro33** [comment]
> It's the Crystallizer plugin,. I have the same issue, but it's gone when I disable that plugin.

It's probably not just Crystallizer, I haven't used it personally.

**Comment by d3vilguard** [comment]
As I see no work being done here - this has been a bug that I have had for years now. Doesn't matter the DE (KDE and Gnome), distro doesn't matter (Arch, Fedora, Tumbleweed). Notifications always begin with a crack. Sound starting is always delayed.

**Comment by wwmm** [comment]
> As I see no work being done here - this has been a bug that I have had for years now. Doesn't matter the DE (KDE and Gnome), distro doesn't matter (Arch, Fedora, Tumbleweed). Notifications always begin with a crack. Sound starting is always delayed.

I suspect this bub's source is more complex than I though. Initially I thought that the shortcomings of the convolver and crystalizer code were the only reason for it. But I use these plugins regularly and somehow I never hear crackling on my system. I admit sound notifications are not something that happens often on my computer. But I would expect the crackling to happen at some point along these years but somehow it doesn't. So something more complex is causing this bug.

**Comment by d3vilguard** [comment]
@wwmm I did have convolver but it's not it. KDE was crackling so much. Remembered this [sauce](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2451). Currently testing it, seems ok for now?
> Niklāvs Koļesņikovs
[@pinkflames](https://gitlab.freedesktop.org/pinkflames) 
While I can't promise this will help, please try creating either `/etc/pipewire/pipewire.conf.d/sample-rates.conf` or `$HOME/.config/pipewire/pipewire.conf.d/sample-rates.conf` and put in it this:

```
context.properties = {
    default.clock.allowed-rates  = [ 48000 ]
}
```

> Then restart the daemons with: `systemctl --user restart pipewire{,-pulse}.socket`
 and retest. If it no longer crackles, the reason for it was either use 
of 44.1 kHz sample rate or the transition itself. If the issue persists,
 you can try checking `cat /proc/asound/card*/*/*/hw_params` while audio is playing to see if it's correctly applied and reporting rate: 48000 (48000/1).

**Comment by wwmm** [comment]
> @wwmm I did have convolver but it's not it. KDE was crackling so much. Remembered this [sauce](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2451). Currently testing it, seems ok for now? So might be actually a general pipewire bug and have nothing to do with easyeffects.
> 
> > Niklāvs Koļesņikovs
> > [@pinkflames](https://gitlab.freedesktop.org/pinkflames)
> > While I can't promise this will help, please try creating either `/etc/pipewire/pipewire.conf.d/sample-rates.conf` or `$HOME/.config/pipewire/pipewire.conf.d/sample-rates.conf` and put in it this:
> 
> ```
> context.properties = {
>     default.clock.allowed-rates  = [ 48000 ]
> }
> ```
> 
> > Then restart the daemons with: `systemctl --user restart pipewire{,-pulse}.socket`
> > and retest. If it no longer crackles, the reason for it was either use
> > of 44.1 kHz sample rate or the transition itself. If the issue persists,
> > you can try checking `cat /proc/asound/card*/*/*/hw_params` while audio is playing to see if it's correctly applied and reporting rate: 48000 (48000/1).

This is forcing PipeWire to do the same sampling rate all the time instead of trying to avoid resampling. But If I am not mistaken this should be its default behavior. WE have to put more than one rate value in that array for it to try to change rate on the fly. I do this. But unless you were also doing the same it is strange this configuration is fixing anything.

**Comment by d3vilguard** [comment]
Unless Arch missing pipewire configuration I have no idea, but had the issue on Tumbleweed way back. KDE has a little sound feedback when you change volume. Very frequently if I were doing nothing and change volume it will play the sound while crackling, or playbacks with start with crackling for a moment. Now I do have to test if for a few days before saying that locking the sampling value fixes it. Linux audio has been a very big hit and miss. I sincerely enjoy being able to do my EQ with easyeffects. Would be awesome if I figure out why BT devices when left on idle for some time refuse to play audio and need to be reconnected.

**Comment by aginiewicz** [comment]
Same issue, fresh NixOS unstable, new Framework 13 Core Ultra, using preset from https://github.com/FrameworkComputer/linux-docs/blob/main/easy-effects/fw13-easy-effects.json - the cracking disappears for me when I disable convolver effect. The cracking appears every time I access plasma audio control, also when I switch tabs there, from devices control to per-app control and back. Any ideas what to try to help debug this?

**Comment by wwmm** [comment]
> Same issue, fresh NixOS unstable, new Framework 13 Core Ultra, using preset from https://github.com/FrameworkComputer/linux-docs/blob/main/easy-effects/fw13-easy-effects.json - the cracking disappears for me when I disable convolver effect. The cracking appears every time I access plasma audio control, also when I switch tabs there, from devices control to per-app control and back. Any ideas what to try to help debug this?

The interaction with the plasma control may be making PipeWire switch to a different latency value. What forces a reinitialization of the convolver. If that is the case forcing a fixed latency value will remove the crackling https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency.

**Comment by aginiewicz** [comment]
> > Same issue, fresh NixOS unstable, new Framework 13 Core Ultra, using preset from https://github.com/FrameworkComputer/linux-docs/blob/main/easy-effects/fw13-easy-effects.json - the cracking disappears for me when I disable convolver effect. The cracking appears every time I access plasma audio control, also when I switch tabs there, from devices control to per-app control and back. Any ideas what to try to help debug this?
> 
> The interaction with the plasma control may be making PipeWire switch to a different latency value. What forces a reinitialization of the convolver. If that is the case forcing a fixed latency value will remove the crackling https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency.

Thanks, that did the trick for me! For some reason force did not work, but I set min and max quantum to same value, and it did the job in my case.

**Comment by wwmm** [comment]
> Thanks, that did the trick for me! For some reason force did not work, but I set min and max quantum to same value, and it did the job in my case.

Good to know. What I think is odd is that I never had to force a fixed on latency on my desktop. This issue is probably one of those where somehow drivers and hardware matter.

**Comment by nickooooooo** [comment]
hello, I wanted to chime in and share a solution for this issue I found at [](https://wiki.cachyos.org/configuration/general_system_tweaks/#granting-realtime-privileges-for-the-user)

sudo pacman -S realtime-privileges
sudo gpasswd -a $USER realtime

although this fix is on the cachyos wiki, I doubt it would have issues on other arch-based distros and also probably work fine with diff distros if there is an equivalent rpm, deb, flatpak, etc. I had rtkit as an optional dependency for pipewire and that seemed to do the job fine until I switched my os to cachy and the crackling returned. the fix with changing the sampling rate didn't help me at all.

the latency adjusting does work, but this just seems like a simpler solution since you don't need to mess with config files (maybe also resolves the crackling without adding 3secs latency or smth?). it seems kinda redundant to have two packages which manage realtime policy, but I need rtkit for lots of stuff besides pipewire, so I guess it's not really a big deal.

one other thing to note; I use many plugins including the crystalizer, and when using pw-top I did see that it had an order of magnitude more latency than most of the other plugins, but disabling it did not help resolve the crackling whatsoever.

**Comment by wwmm** [comment]
>although this fix is on the cachyos wiki, I doubt it would have issues on other arch-based distros and also probably work fine with diff distros if there is an equivalent rpm, deb, flatpak, etc. I had rtkit as an optional dependency for pipewire and that seemed to do the job fine until I switched my os to cachy and the crackling returned. the fix with changing the sampling rate didn't help me at all.

I wonder what cachyos is actually doing here. It is not like EasyEffects does not have its audio processing thread with realtime priorities. It has. PipeWire handles this just fine here on Arch Linux without any need for the user to be in a realtime group. Maybe the fix is undoing something else cachyos was doing do EasyEffects threads.

**Comment by theofficialgman** [comment]
Same issue here. Seems to occur primarily with the convolver.

**Comment by theofficialgman** [comment]
It comes through as a crackle when audio is playing but if I pause the audio and then trigger the "crackle" by poping up the audio menu, I hear a split second of the audio that I had previously had playing.

**Comment by PistachioGuy** [comment]
On my computer I have my pipewire buffer size set to 256 and sample rate at 82200 (for low latency guitar)
Configured like that, I hear a lot of crackles when autogain is enabled, but without autogain i hear none.
If I reset these values to their default values of 1024 and 48000, I get no crackle at all

**Comment by wwmm** [comment]
> On my computer I have my pipewire buffer size set to 256 and sample rate at 82200 (for low latency guitar) Configured like that, I hear a lot of crackles when autogain is enabled, but without autogain i hear none. If I reset these values to their default values of 1024 and 48000, I get no crackle at all

What you are describing is the usual situation where the computer is not being able to process audio buffers fast enough. Each case may have a different reason for that. The library `libebur128` used by our autogain plugin can be quite heavy. When forcing a low latency value the stress on the system increases and not all hardware combination is capable of hadnling that.

Unfortunately there is not much that can be done in this case. Sometimes it is possible to tweak the way PipeWire configures its interaction with the ALSA drivers a little and reduce crackling. But in most cases the only reliable solution is increasing the latency.

**Comment by wwmm** [comment]
Maybe things can get better if you boot your system with the kernel option `threadirqs`. Or using a kernel patched for realtime audio processing.

**Comment by AzyWng** [comment]
I've been getting occasional crackling during recording and some audio playback as well. I'm on Ubuntu 24.04.2 LTS, not using any presets, just using both the Noise Cancellation and Compressor plugins while recording onto Audacity. I haven't been using EasyEffects to change audio output, though.

If there's any solution someone can suggest that would work for me, I'd love to know.

**Comment by wwmm** [comment]
> I've been getting occasional crackling during recording and some audio playback as well. I'm on Ubuntu 24.04.2 LTS, not using any presets, just using both the Noise Cancellation and Compressor plugins while recording onto Audacity. I haven't been using EasyEffects to change audio output, though.
> 
> If there's any solution someone can suggest that would work for me, I'd love to know.

@AzyWng in these cases the first thing I do is looking at the output of `pw-top`. Specifically to the error column and the `QUANTUM` value displayed at the soundcard line. Sometimes audio players may request low latency. What makes PipeWire dynamic latency switching choose a quantum value that may be too low for the system to handle.

If too low latency is the problem temporarily setting the QUANTUM value to a fixed and higher power of 2 value like `2048` or `4096` https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency should make the crackling go away.

**Comment by AzyWng** [comment]
Setting the QUANTUM value to 2048 seems to have lessened the crackling some, but I still notice the occasional moment where there's a pop or other noise when I play back my audacity recording.

When I set it to 4096 I noticed Audacity's frame rate seemed a little slower and the program will occasionally pause mid-playback, but there's way less crackling - it's still kind of present, but only if I listen very carefully.

What should I be paying attention to in the Error column? Even after setting it to 4096, I'm still getting an "ERR" of 28, and I hope that's not a sign of further problems.

**Comment by wwmm** [comment]
>What should I be paying attention to in the Error column? Even after setting it to 4096, I'm still getting an "ERR" of 28, and I hope that's not a sign of further problems.

That error count is usually an indication that the system is not being able to process audio buffers fast enough. In the most concerning cases it keeps increases and doesn't take long to reach a few thousands. As you error count is still low your system is just having some occasional moments where it can't keep up.

**Comment by easiers** [comment]
> hello, I wanted to chime in and share a solution for this issue I found at https://wiki.cachyos.org/configuration/general_system_tweaks/#granting-realtime-privileges-for-the-user
> 
> sudo pacman -S realtime-privileges sudo gpasswd -a $USER realtime

Tried this and still not working for me, unsure if it's even down to EasyEffects because I don't know what to do to pinpoint the source of the problem.

**Comment by wwmm** [comment]
> Tried this and still not working for me, unsure if it's even down to EasyEffects because I don't know what to do to pinpoint the source of the problem.

Unfortunately a bug in  `xdg-desktop-portal` is not allowing PipeWire to get realtime priority. I think that xdg-dekstop-portal master branch has been fixed but no new release has been done yet.

**Comment by easiers** [comment]
> Unfortunately a bug in `xdg-desktop-portal` is not allowing PipeWire to get realtime priority. I think that xdg-dekstop-portal master branch has been fixed but no new release has been done yet.

Ahh I see, appreciate the comment. Will be waiting then!

**Comment by GavinCoded** [comment]
Does anyone know how to fix this yet? It seems to have started after I enabled the Crystalizer plugin my audio crackles whenever I get a Discord notification on GNOME Fedora 42.

I disabled the plugin, and it still happens. I even completely uninstalled EasyEffects, but the issue persists. Is there any way to fix it?

**Comment by akibanator** [comment]
I have always experienced these sound issues reported by the author, but due to a lack of knowledge, I was never able to resolve them.

I would like to share some tests I performed on my PC. I noticed that the problem occurs when there is a change in the quantum value of the output device, which is why fixing the quantum value resolves part of the issue.

Monitoring with `pw-top`, when opening the panel reported by @Exioncore, a new process appears:

<img width="1030" height="44" alt="Image" src="https://github.com/user-attachments/assets/c3b98c89-eb1b-4777-b424-fb1a8f8a8049" />

<img width="403" height="229" alt="Image" src="https://github.com/user-attachments/assets/904b26c1-9cce-4971-b4de-af6fc833f35b" />

It can be observed that the **quantum** value of the new process, which is part of **KDE**, is 1 and the **rate** is 25. This causes the quantum of the default output device to adapt to the minimum value, briefly producing a pop sound when opening the panel.

This behavior also occurs with other applications that force a change in the quantum value of the default output device.

In any case, fixing the quantum value resolves the issue, but it’s more of a workaround since it increases latency.

**Comment by wwmm** [comment]
> I noticed that the problem occurs when there is a change in the quantum value of the output device, which is why fixing the quantum value resolves part of the issue.

Some of the plugins we use (mostly the ones used through LV2) are able to better handle changes to the audio buffers size (quantum) on the fly. While others still require a complete destruction and recreation of the filter instance. In a situation like the one you reported where a huge change in audio buffer size happens some noise may happen indeed.

**Comment by KyuVulpes** [comment]
I don't know if this is the right place for this, but I have sporadic audio crackling when my system is under 30% total system load. And according to pw-top, all the errors are coming from `ee_soe_*` First I had an equalizer to tamper down the highs, and that was the one throwing all the errors. Removed it then the bass amplifer started causing the errors, so on until no more effect layers were left. At which point pw-top reported `ee_soe_spectrum` was causing the errors. Here is a screenshot of pw-top where EasyEffects had no effects/filter active.

<img width="837" height="261" alt="A screenshot showing ee_soe_spectrum is throwing a ton of errors." src="https://github.com/user-attachments/assets/dd6b5c50-9c88-42bf-aa8d-6cff90b286bc" />

I am fairly certain there is an issue with EasyEffects, at least in my case, but unsure as it seems to have no issue on my Steam Deck. The specs of my main system is as follows:

CPU:    Ryzen 7 5800X3D
RAM:    128GB DDR4
GPU:    Radeon RX 7900 XT
MB:     Gigabyte Aorus Elite WiFi
Kernel: 6.17.5-Zen

**Comment by wwmm** [comment]
>I am fairly certain there is an issue with EasyEffects, at least in my case, but unsure as it seems to have no issue on my Steam Deck.

In the machine that has errors run `chrt -ap pid` where pid is EasyEffects pid number. Do you see a `SCHED_RR` in the output? If not the crackling may be because realtimes priorities are lacking. A bug in xdg-desktop-portal caused that in some distributions. It has already been fixed in their latest version. 

I also see pipewire is using a quantum of 128 as target. Not all hardware combinations handle this well. It depends on CPU, soundcard driver and hardware, etc. You may have to force a higher pipewire quantum in this machine. OR launching the app with `PULSE_LATENCY_MSEC` set to a high value like 100 ms.

**Comment by ridesdragons** [comment]
I'm also getting crackling with EasyEffects. recently migrated from windows since win10 hit EoL and there was no way I was getting 11. however, I've relied on the "Loudness Equalization" option in windows, and the only method I've been able to find to replicate it is through easyeffects... but the crackling is driving me nuts!

running cachyos with kde plasma, wayland (in case any of these matter), cpu's an AMD ryzen 5 5600x, gpu's an nvidia 1660 Ti.

been trying various suggestions seen here and elsewhere with no relief. tried installing realtime-privileges, but all the guides simply jumped to "now add your user to the group" without explaining _how to actually do that_ (someone helped me with this eventually btw, also didn't help). I saw mention that xdg-desktop-portal caused this, but was fixed in the latest version, _but I have the latest version_ and it still persists. and I tried running `chrt -ap pid` to see the schedule, and it is indeed not `SCHED_RR` (it's "OTHER" instead), but I don't know how to fix that.

turning off easyeffects seems to turn off the crackling (as far as I can tell, the audio is overall much quieter so I have to ramp the volume way up), but then I don't get loudness equalization, which [makes games unplayable](https://www.reddit.com/r/factorio/comments/8qgt9k/factorio_noise_disparity_fix/) and videos unwatchable, but I'm failing to find alternative solutions, bleh.

kinda hard being a new linux user when all the guides expect you to have been using it for quite some time lol

**Comment by wwmm** [comment]
@ridesdragons what do you see in the output of the command `pw-top` when the crackling happens? In particular the quantum column at your soundcard line. Maybe increasing the quantum value will help as it is related to latency.

When playing games it will probably help to launch them with `PULSE_LATENCY_MSEC=60` or higher values because they usually request latency values that are way lower that some systems are able to handle.

>but I have the latest version and it still persists

Which version do you have installed? Here on Arch Linux I have `xdg-desktop-portal 1.20.3`

**Comment by ridesdragons** [comment]
ah, right as I was heading to bed lol

> Which version do you have installed?

1.20.3-2.1 (on bauh), so should be same version as you

> what do you see in the output of the command pw-top when the crackling happens? In particular the quantum column at your soundcard line. Maybe increasing the quantum value will help as it is related to latency.

gonna be honest, I don't understand what quantum even means or why we're using physics terms to describe latency. as far as I can tell, though, the quantum column is static. alsa_output.bunch-of-other-stuff says 2048 (this should be the soundcard line), firefox says 3600, all of the ee_soe_* stuff says 0 (everything else in the list also says 0)

> When playing games it will probably help to launch them with PULSE_LATENCY_MSEC=60 or higher values because they usually request latency values that are way lower that some systems are able to handle.

you talking about like with launch options in steam or heroic? noted I suppose, but the crackling happens when I'm watching youtube videos, too. that said, it's inconsistent. sometimes it'll happen constantly whenever there's sound, sometimes it'll be fine. it gets much worse if I join a discord vc or start streaming, so it is impacted by load, but it _does_ happen when the only thing I'm doing is watching a video

**Comment by wwmm** [comment]
> I don't understand what quantum even means or why we're using physics terms to describe latency

Lol 😄 . It is not that kind of quantum. In this context it refers to the number of elements in the audio buffer array. The array size is related to the latency.

>alsa_output.bunch-of-other-stuff says 2048 (this should be the soundcard line)

This is usually fine. When games are running they usually request low latency values that make PipeWire select 128 as quantum value. Some systems do not handle that well.

>you talking about like with launch options in steam or heroic?

It is one way to do that. It is also possible to do it inside /etc/environment so all programs see it. But I would only do that if setting that variable actually helps.

**Comment by ridesdragons** [comment]
> This is usually fine. When games are running they usually request low latency values that make PipeWire select 128 as quantum value. Some systems do not handle that well.

_ah, I see._ yes, if I boot up a game, it does indeed drop down to 128, with the game showing up with 240. rebooting the game with the pulse latency launch option raises it to 512 (game is now 720).

I guess I'll test tomorrow to see if I still get obvious crackling while playing stuff with the pulse latency launch option inserted. in the meanwhile, I would like to know how exactly I should be getting EE to be realtime... or is that just not on the table for me? (as I mention earlier, instead of `SCHED_RR` it's `SCHED_OTHER`)

**Comment by r3tr0g4m3r** [comment]
> 
> kinda hard being a new linux user when all the guides expect you to have been using it for quite some time lol

I have mitigated this problem in Manjaro (Arch or Cachy should be the same) like this:

Create a new file called "10-crackling-fix.conf" in the "/etc/pipewire/pipewire.conf.d" folder:
_example edit with nano:_
` sudo nano /etc/pipewire/pipewire.conf.d/10-crackling-fix.conf  `

In this file override the quantum properties (latency) from the "default" to 4096:

```
context.properties = { 
    default.clock.quantum       = 4096
    default.clock.min-quantum   = 256
    default.clock.max-quantum   = 8192
}
```

Reboot and look at pw-top, "quant" column should display 4096, this fix adds latency, you should first set it to 1024 and try the other fixes first before trying greater values (2048,4096, 8192) since adding too much latency brings problems of audio sync.

- Fix 2
`/etc/udev/rules.d/50-scaling-governor.rules`
```
SUBSYSTEM=="rtc", KERNEL=="rtc[0-9]", ACTION=="add|change", RUN="/usr/bin/bash -c 'echo 2048 | tee /sys/class/rtc/rtc0/max_user_freq'"
SUBSYSTEM=="cpu", KERNEL=="cpu[0-9]", ACTION=="add|change", RUN="/usr/bin/bash -c 'echo 2048 | tee /proc/sys/dev/hpet/max-user-freq'"

```

- Fix 3
` ~/.config/wireplumber/wireplumber.conf.d/00-disable-suspension.conf`
```
monitor.alsa.rules = [
  {
    matches = [
      {
        # Matches all sources
        node.name = "~alsa_input.*"
      },
      {
        # Matches all sinks
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
# bluetooth devices
monitor.bluez.rules = [
  {
    matches = [
      {
        # Matches all sources
        node.name = "~bluez_input.*"
      },
      {
        # Matches all sinks
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
```

- Fix 4
`~/.config/wireplumber/wireplumber.conf.d/00-alsa-config.conf`
```
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.period-size   = 1024
        api.alsa.headroom      = 8192
      }
    }
  }
]
```

_reboot or restart services:_
systemctl --user restart wireplumber pipewire pipewire-pulse

:wink:

**Comment by ridesdragons** [comment]
alright, so, I've spent the day with the `PULSE_LATENCY_MSEC=60` launch option on in games, and while the crackling isn't _gone_, it's certainly been greatly reduced. however, I noticed that if I join a voice call in discord, discord asks for a quantum level of 360, lowering it down from 512 to 256... _thanks discord._

I have not attempted retrogamer's fix - it initially looked far too extreme (and after edits, it turns out it definitely was lmao). over half a second of delay is _crazy_, and as someone who used to play rhythm games all the time, I very much don't want to have to put up with such a noticeable delay lmao

do have to ask, though, I did see some mention somewhere that since the bug happens when EE is suspended due to silence, that _stopping it from ever suspending to begin with_ would work around the realtime privileges being revoked issue, is that what fix 3 does?

also, can someone else vet the fixes and ensure that these are in fact sane fixes and won't cause serious issues lmao. just wanna be sure before I _accidentally_ rm rf the whole thing, you understand lol

**Comment by wwmm** [comment]
> I did see some mention somewhere that since the bug happens when EE is suspended due to silence, that _stopping it from ever suspending to begin with_ would work around the realtime privileges being revoked issue, is that what fix 3 does?

Saying that EE is suspended isn't correct. The audio filters and virtual devices can be suspended by pipewire after some time of inactivity. Some hardware causes noises when coming back from suspension. And forcing the pipeline to keep running may flush some old data inside the plugins that could be perceived as noise. But there is an obvious drawback. CPU will be wasted processing silence...

Fix number two should do nothing for most users because nowadays the hpet clock from the motherboard isn't really used. The tsc clock provided by the CPU is what is used by modern Linux systems.

Fix number four may help. But usually you have to test several values and find the one that is good for your system.

**Comment by ridesdragons** [comment]
`~/.config/wireplumber/wireplumber.conf.d/00-alsa-config.conf` does not exist on my system. however, `/usr/share/wireplumber/wireplumber.conf.d/alsa-vm.conf` does, and it does contain the code you mentioned (monitor.asla.rules). is that the one I should modify? also the headroom in my file is 2048, what would quadrupling the headroom do?

sorry for the questions and thanks for the help, btw

**Comment by r3tr0g4m3r** [comment]
> `~/.config/wireplumber/wireplumber.conf.d/00-alsa-config.conf` does not exist on my system. however, `/usr/share/wireplumber/wireplumber.conf.d/alsa-vm.conf` does, and it does contain the code you mentioned (monitor.asla.rules). is that the one I should modify? also the headroom in my file is 2048, what would quadrupling the headroom do?
> 
> sorry for the questions and thanks for the help, btw

You need wireplumber installed in your system, if the file doesn't exist you can create it, with the wireplumber service running, it reads this file and overrides the setting, according to the [official docs](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting#underrununderflow-and-broken-pipe-errors):

`Applications not providing data fast enough and not enough headroom in the device to recover. Increase headroom.`

Files in "~" are executed only for the user, the others in "/etc" or "/usr" are for the whole system.

My post is just a collection of fixes from the Arch Linux [Wiki ](https://wiki.archlinux.org/title/PipeWire)and the official [documentation](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting).

**Comment by AzyWng** [comment]
I've tried increasing the quantum value using force-quantum 2048, but I still occasionally have crackling sounds. This is without any output plugins, and just "Noise Reduction" as an input plugin. I'm not sure how to resolve the issue either...

**Comment by wwmm** [comment]
> I've tried increasing the quantum value using force-quantum 2048, but I still occasionally have crackling sounds. This is without any output plugins, and just "Noise Reduction" as an input plugin. I'm not sure how to resolve the issue either...

Hum... This plugin uses the RNNoise library. And it only works with 48 kHz. What means we have to do resampling. Maybe there is a problem in how the resampling is done. Try to force pipewire to use a fixed resampling rate for a while and pay attention to see if after that there are still noises.

**Comment by AzyWng** [comment]
Gave that a try. Now I'm not sure what else happened, but now when I try to configure the Noise Reduction effect on the Input section, I get the message "The Noise Reduction effect was disabled when EasyEffects was compiled. This is perhaps since the software required for this effect, "RNNoise", was not available. Consider using the Easy Effects Flatpak package or building your own EasyEffects package.

I know that's a separate issue, but I would like to be able to avoid noise crackling and be able to use EasyEffects' noise cancellation at the same time. That said, after forcing the resampling rate to be 48000, I haven't noticed any crackling with audio playback so far.

**Comment by wwmm** [comment]
>That said, after forcing the resampling rate to be 48000, I haven't noticed any crackling with audio playback so far.

Hum... So either we have an issue in our resampling code or PipeWire's dynamic sampling rate switching is causing some kind of side effect. I have to remember to investigate this.

**Comment by windigerbus** [comment]
Thought I'd put my experience here for anyone stumbling across this.
For me, this only occurred when I was in a Discord voice chat for a few minutes and had EE open.
From the output of `pw-top`, I could figure out the app was forcing a very low quantum value (I think 150?) while I was in a voice chat.
So, based on retrogamers fix, I created the file `/usr/share/pipewire/pipewire.conf.d/10-crackling-fix.conf` and added only the following:
```
context.properties = {
    default.clock.min-quantum = 384
}
```
After rebooting, the issue completely disappeared.

**Comment by MiguVT** [comment]
I fixed this editing:

`~/.config/pipewire/pipewire.conf.d/99-crackling-fix.conf`:
```conf
context.properties = {
    default.clock.rate = 48000
    default.clock.quantum = 2048
    default.clock.min-quantum = 1024
    default.clock.max-quantum = 4096
}
```

`~/.config/pipewire/pipewire-pulse.conf.d/99-crackling-pulse-fix.conf`:
```conf
pulse.properties = {
    pulse.min.quantum = 1024/48000
    pulse.default.req = 2048/48000
}
```
