### ISSUE TITLE
Preset autoloading broke completely

### ISSUE THREAD

**Issue by arcjth** [wwmm/easyeffects#4320]
### EasyEffects Version

8.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

bazzite (fedora kinoite image)

### Describe the bug

easyeffects doesn't detect changes in port routing

<img width="1374" height="558" alt="Image" src="https://github.com/user-attachments/assets/322a35e6-64a2-472a-8852-3325bc8d984c" />

<img width="1375" height="569" alt="Image" src="https://github.com/user-attachments/assets/a06d55a4-3f6b-4b74-b562-2a98e4711d0d" />

### Expected Behavior

assign a preset with headphones plugged, see that it has been assigned to the default device with port heaphones, remove headphones and assign preset to the speakers, see that the preset has been assigned to default device with port speakers.

### Additional Information

i have one preset for my headset and one for the integrated speaker.
my drivers don't interpret headphones as different devices so i was relying on the port autoload parameter to assign each preset accordingly, but that's now broken as removing and inserting the headphones won't make any changes to the device easyeffects will assign the preset.

**Comment by wwmm** [comment]
Did you try to recreate the autoloading profiles? EasyEffects 8 is getting the routing information through a different PipeWire property. As pipewire names the routing slightly differently in this new property the autoloading profiles file has to be recreated.

**Comment by wwmm** [comment]
>easyeffects doesn't detect changes in port routing

Hum... EasyEffects does not really detect anything. PieWire is supposed to send the event about the change. I wonder if it is not doing that for your particular hardware in the new property we use.

**Comment by wwmm** [comment]
It is a long story. Before this new pipewire node property we had to listen to two different signals to have the full information needed for the autoloading. But as everything that is asynchronous sometimes the information came in an order that broke easyeffects logic. Now that pipewire has created a routing property for each node the obvious thing to do was getting all the information from a single event related to the node object.

**Comment by wwmm** [comment]
Kill easyeffects and restart it in debug mode `easyeffects --debug`. After that do what is necessary to change your device routing so we can see if pipewire is sending the proper events.

**Comment by wwmm** [comment]
Something else that may help to understand what is going on is running
```
pw-cli list-objects Node
```
in order to find your soundcard device id number. And then
```
pw-cli info number
```
. Pay attention to what happens to the properties `device.profile.name` and `device.profile.description` and `device.routes`. Does any of them change when you plug your headphone?

**Comment by arcjth** [comment]
`device.profile.name`, `device.profile.description` remain the same, `device.routes` says there's 2 but doesn't change either.

**Comment by arcjth** [comment]
in fact i can't see any changes anywhere, headphones plugged or not. i can't confirm it wasn't like this before but "hardware profile" on easy effects used to change and explicitly tell if it was the heaphones port or the speaker, so what changed is more on how pipewire now handles this?

**Comment by wwmm** [comment]
> `device.profile.name`, `device.profile.description` remain the same, `device.routes` says there's 2 but doesn't change either.

Hum... That is unfortunate. And probably something that should be fixed on pipewire's side. It does not make sense to set this information once and never update it. But until this happens we will need a workaround. Probably listen to the old signal and try to update this one on our side somehow. But the fact pipewire names the routing differently  in each possible way to get its name writing a workaround will be annoying.

>so what changed is more on how pipewire now handles this?

It still has the other signal we used to get the device routing. I did not want to use it because we had other problems with it related to synchronization. That signal may come after or before we are notified about new nodes and node changes. So there were cases were EasyEffects was not able to match nodes and routings.

**Comment by wwmm** [comment]
And to make things even more confusing PipeWire does update these properties for one of my microphones. This one has an analogic and a digital profile. When I change the profile in pavucontrol pipewire retains the node id and properly updates the device routing value. So the issue depends on hardware...

Unfortunately my soundcard is one of those with different names for each port and one port dedicated to the headphone. So it is not ideal I am the one reporting this issue to them. If possible try to report to them that pipewire is not updating these properties on your hardware. In the mean time I will think about some kind of workaround.

**Comment by wwmm** [comment]
By the way which pipewire version do you have installed in your system?

**Comment by wwmm** [comment]
It is also worth testing if manually changing your soundcard profile in pavucontrol after plugging your headphones makes it update the routing property. Maybe it has a bug that is not allowing the property update when the headphone is plugged but things may work when triggered manually in pavucontrol or your desktop audio manager.

**Comment by arcjth** [comment]
everywhere else seems to properly use each port, plugging the headphones makes the volume change to the last used headphone's volume and vice-versa, and pavucontrol shows both ports: speaker and headphone
when the speaker is at use, headphone is "unplugged", and when headphones are connected, speakers become unavaliable, selecting any of the unavailiable ones throws the audio to the easy effects sink device. there are some different profiles but they don't help the problem at all, either keeping the same behavior or messing with sound: `analog stereo duplex`, `analog stereo output`, `analog stereo input` and `pro audio`.
`pipewire --version` outs this:
>pipewire
Compiled with libpipewire 1.4.9
Linked with libpipewire 1.4.9
> 
so i guess 1.4.9?

**Comment by wwmm** [comment]
> so i guess 1.4.9?

Yes. I've decided to open an issue at PipeWire's page https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4974 and I asked if this property is supposed to be updated or not. Let's see what they say.

**Comment by HackaN** [comment]
FYI I had the same issue with autoloading not working when switching outputs. I downgraded from th flathub flatpak to the fedora flatpak (v 7.2.5) and it's working properly now... So it doesn't seem to be something with pipewire.

**Comment by wwmm** [comment]
>So it doesn't seem to be something with pipewire.

As they are not properly updating the new property we use it definitely has issues. Easyeffects 7.2.5 is working because it uses a more complex approach based on more pipewire events. But as explained above that approach fails in some situations.

**Comment by arcjth** [comment]
> . I downgraded
> 
that's probably what i'll do for now too. if the new method works for most and we are outliers, it could be useful to have some property that would change to the old method for autoloading as a "compatibility mode" but i do remember occasional synchronization problems would occur when changing the plug state of the headphones, it was quite rare though.
it's clearly changing something that is tracable but surely not anything i managed to find on my own
```shell
> pactl subscribe
Event 'change' on card #61
Event 'change' on sink #74
Event 'change' on source #74
```
but diff-ing `pw-cli info 61` or `pw-cli info 74` between plug states shows no change at all, am i missing something? really confusing

**Comment by wwmm** [comment]
> but diff-ing `pw-cli info 61` or `pw-cli info 74` between plug states shows no change at all, am i missing something? really confusing

Our previous approach used the events from what pipewire calls "Devices" together with the ones it calls "Nodes". My guess is that on your hardware it updates the "Device" routing property but not the one from "Nodes". Try to look at the properties from the objects shows at the output of
```
pw-cli list-objects Device
```
After getting the correct id number run `pw-cli info number`. You will probably see the right device routing there.

**Comment by wwmm** [comment]
I've sent a question about this to pipewire's matrix channel. BEfore implement a workaround or going back to the previous approach I would like to know from them if `device.profile.name` not being updated is intended or a bug.

**Comment by wwmm** [comment]
After talking to them the conclusion is that there is no reliable way to trigger a preset autoload based on headphones plugging. It is either how we are now or the randomness that could happen in the previous approach. As in the end we will have users that won't have a functional autoload anyway I suppose it is better to return to the previous approach... It seems to hurt less people.

**Comment by tannerellen** [comment]
On my system (framework 13 laptop) I can't even set an auto loader for the headphone port because it's all just detected as the main audio device after the update to easyeffects 8.0. Maybe that's related to the port change detection? Headphones used to show up as an option but now regardless if my headphones are plugged in or not it's just showing the main audio device as my only option.

**Comment by wwmm** [comment]
> On my system (framework 13 laptop) I can't event set an auto loader for the headphone port because it's all just detected as the main audio device after the update to easyeffects 8.0. Maybe that's related to the port change detection? Headphones used to show up as an option but now regardless if my headphones are plugged in or not it's just showing the main audio device as my only option.

You probably have the kind of hardware where the node name remains the same and the routing/profile changes internally. These are the users for which the autoload is not working right now. The cases where pipewire sets a new node name are fine.

In the next days I will try to fix this. Returning to the old way that is also broken in some cases was not in my plans but so far no better solution has been found.

**Comment by wwmm** [comment]
@Digitalone1 the first round of fixes to presets autoloading is already in our master branch. I think things should be better now. But it is important that everyone that had it broken try to test. Unfortunately my hardware is one of those where this issue does not happen.

If possible test the fallback preset too.

**Comment by wwmm** [comment]
It will be necessary to recreate the autoloading profile.

**Comment by tannerellen** [comment]
My headphone jack still isn't showing as an audio device after installing from git. Pavucontrol picks up that the headphones are plugged in but easyeffects only shows the main audio device means autoloading won't trigger when I plug or unplug headphones.

https://github.com/user-attachments/assets/4f16746f-f657-41fb-96b3-012635cf4be4

**Comment by wwmm** [comment]
> My headphone jack still isn't showing as an audio device after installing from git. Pavucontrol picks up that the headphones are plugged in but easyeffects only shows the main audio device means autoloading won't trigger when I plug or unplug headphones.
> 
> https://github.com/user-attachments/assets/4f16746f-f657-41fb-96b3-012635cf4be4

In your case the device line probably  will remain the same because pipewire does not change it. What should have happened is a change in the hardware profile line below the device selector. 

Run easyeffects in debug mode `easyeffects --debug`. Is there a line talking about new device profile when you plug your headphone?

**Comment by Digitalone1** [comment]
@wwmm Now I have the profile visible:

<p><img width="705" height="98" alt="Image" src="https://github.com/user-attachments/assets/e67e0ecb-cc51-42ee-b00e-7a0b7a6f0a1f" /></p>
<p><img width="705" height="98" alt="Image" src="https://github.com/user-attachments/assets/2e846d11-c7f4-4cdf-9141-7d54edc71e65" /></p>

**Comment by tannerellen** [comment]
> Run easyeffects in debug mode `easyeffects --debug`. Is there a line talking about new device profile when you plug your headphone?

Nothing shows when plugging in or unplugging from the headphone jack.

https://github.com/user-attachments/assets/d7ba2fd8-7b9e-409d-bb82-0bf6ef1f276b

**Comment by wwmm** [comment]
>Nothing shows when plugging in or unplugging from the headphone jack.

Ok. It seems that on your hardware pipewire does not update the profile property no matter from where it comes. I will try a new solution based on the route property.

**Comment by wwmm** [comment]
New approach based on the device route like in the past is in our master branch. Its strings aren't as user friendly as the one from the profile property. But there is no point in the messages being better if pipewire can't update them.

I also added to our preferences window a new "preset" section that has a setting that allows the delay between receiving a new route and the preset autoload to be set. I hope this way users with hardware that has weird events timing can somehow compensate with enough delay for all the information needed to be in place.

@tannerellen let me know how things are now.

**Comment by tannerellen** [comment]
> [@tannerellen](https://github.com/tannerellen) let me know how things are now.

Yep, that did it. Works great now. The new setting is a good idea too. In my case I could set it to 0 ms and it still works great so doesn't appear to be running into any timing issues for me.

Really appreciate you taking the time to fix this. I love the app so it's great to not have to downgrade. Really blown away you were able to resolve this so quickly. Many thanks!!

**Comment by wwmm** [comment]
I think we can close this issue.

**Comment by martin-kokos** [comment]
Sorry for necroposting, but I think it might be related.
I had broken autoloading. I killed easyeffects with `easyeffects -q` and saw these messages:
```
easyeffects: presets_directory_manager.cpp:140  Old /home/x/.config/easyeffects/irs directory detected. Migrating its files to /home/x/.local/share/easyeffects/irs
easyeffects: presets_directory_manager.cpp:149  Could not copy any file. Aborting migration of /home/x/.config/easyeffects/irs
easyeffects: presets_directory_manager.cpp:140  Old /home/x/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/x/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149  Could not copy any file. Aborting migration of /home/x/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140  Old /home/x/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/x/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149  Could not copy any file. Aborting migration of /home/x/.config/easyeffects/autoload/input
```
I checked the directories, they were migrated but empty directories were left behind for whatever reason.
I deleted them and autoloading seems to have been fixed.

**Comment by wwmm** [comment]
> I checked the directories, they were migrated but empty directories were left behind for whatever reason.
> I deleted them and autoloading seems to have been fixed.

Strange. The older paths existence should not matter. I still have some of them and as far as I can see they are ignored.

The migration code first implementation deleted the older paths. It worked well for me and some users. But for reasons I could never understand the migration failed badly for some people. The presets were deleted from the older location without being copied to the new one. So I decided to just copy the presets to the new location and leave the older ones there.
